### ISSUE TITLE
Improve scijava.platform.* properties for native artifact classifiers

### ISSUE THREAD

**Issue by ctrueden** [scijava/pom-scijava-base#30]
A particular goal is to make Mac M1 better supported. E.g. #29 sets the `scijava.platform.bits` to 64, but the architecture name is really arm64. See the #29 comment thread for important details here.

An example project in the SciJava umbrella that would benefit from these improvements is FLIMLib; see flimlib/flimlib#60.

---------------

@mkitti [wrote](https://gitter.im/fiji/DevOps?at=620185a3b8b082448221ea1e):
<blockquote>

It would be nice if we could align some of the definitions with those of other communities. For example, [here](https://anaconda.org/conda-forge/openjdk) are the platforms where Zulu openjdk 11 is available on conda-forge.

I'm not sure if I really under their architectures that well myself, but perhaps someone at https://gitter.im/conda-forge/conda-forge.github.io might be able to provide more information.

Over in Julia, we use a cross-compilation framework to support these platforms. The framework is not exclusive to Julia, so this could be useful if you want to support a wide variety of platforms with a single build recipe.
```julia
julia> using BinaryBuilder

julia> supported_platforms()
16-element Vector{Platform}:
 Linux i686 {libc=glibc}
 Linux x86_64 {libc=glibc}
 Linux aarch64 {libc=glibc}
 Linux armv6l {call_abi=eabihf, libc=glibc}
 Linux armv7l {call_abi=eabihf, libc=glibc}
 Linux powerpc64le {libc=glibc}
 Linux i686 {libc=musl}
 Linux x86_64 {libc=musl}
 Linux aarch64 {libc=musl}
 Linux armv6l {call_abi=eabihf, libc=musl}
 Linux armv7l {call_abi=eabihf, libc=musl}
 macOS x86_64
 macOS aarch64
 FreeBSD x86_64
 Windows i686
 Windows x86_64

julia> triplet.(supported_platforms())
16-element Vector{String}:
 "i686-linux-gnu"
 "x86_64-linux-gnu"
 "aarch64-linux-gnu"
 "armv6l-linux-gnueabihf"
 "armv7l-linux-gnueabihf"
 "powerpc64le-linux-gnu"
 "i686-linux-musl"
 "x86_64-linux-musl"
 "aarch64-linux-musl"
 "armv6l-linux-musleabihf"
 "armv7l-linux-musleabihf"
 "x86_64-apple-darwin"
 "aarch64-apple-darwin"
 "x86_64-unknown-freebsd"
 "i686-w64-mingw32"
 "x86_64-w64-mingw32"
```

https://binarybuilder.org/
https://github.com/JuliaPackaging/Yggdrasil (recipe repository)
On Windows, I'm starting to anticipate the need to do distinct UCRT builds in a few years.

</blockquote>

**Comment by ctrueden** [comment]
Architectures with synonyms:

| arch | description | synonyms |
|---|---|---|
| x86_32 | x86 32-bit | x86, i386, i486, i586, i686 |
| x86_64 | x86 64-bit | amd64 |
| ia64 | [Itanium](https://en.wikipedia.org/wiki/IA-64) | |
| ppc | PowerPC (32-bit) | powerpc |
| ppc64 | PowerPC 64-bit (big endian) | |
| ppc64le | PowerPC 64-bit little endian | |
| arm | ARM... but which version and features? | |
| arm64 | ARM 64-bit (e.g. Mac M1) | aarch64 |
| armhf | ARM 32-bit with "hard float" support | |
| armv6 | ARM v6 (32-bit) | |
| armv6hf | ARM v6 with "hard float" support (32-bit) | |
| armomgwtf | [There are so many...](https://en.wikipedia.org/wiki/List_of_ARM_microarchitectures) | |

**Comment by ctrueden** [comment]
@paddyroddy I released pom-scijava-base 15.0.0, which changes how the `scijava.natives.classifier` property gets calculated. I discarded the `scijava.platform.bits` property in favor of a more general `scijava.platform.arch`, which is mostly equal to `os.arch` (it is for arm64, for example), except for x86 platforms it strips the `x86_` prefix, so e.g. `amd64` becomes just `64` in line with the current native-lib-loader convention. This approach will automatically correct in more cases in an extensible way, but in cases where it does the wrong thing, we can always override it case by case, as was done for x86 architecture. (Or, you know, some day we could change the native-lib-loader convention, which is confusing IMHO.)

I'll be cutting a new pom-scijava release very soon, and then I can update flimlib to extend it, and release a new flimlib and maybe downstream libraries as needed...

Of course, none of this actually deploys an M1 build of flimlib, since we're waiting on actions/runner#805 to be completed, as you mentioned. I know we talked about doing a manual deploy of the M1 build you made, and I still want to do that, but I'm insanely busy with a paper deadline through next week, then on vacation for two weeks. If you absolutely need this sooner than 3-4 weeks from now, ping me again and I'll make time to do it.

**Comment by paddyroddy** [comment]
thanks @ctrueden! As I mentioned here https://github.com/flimlib/flimlib/issues/60#issuecomment-1039214138 I've got it to build locally so not urgent from my end. Good luck with the deadline

**Comment by ctrueden** [comment]
With 804fa6734871b402e55cce04833cd71c63d1b3cb, pom-scijava-base now defines naming conventions for javacpp- and jogl-based native classifier artifacts. With 81f583d6ac8e1b6b3eed5cd3a4c66146381be5ed, this naming is extended to support arm64/aarch64 (e.g. Mac M1).
