### ISSUE TITLE
Consider adding cobertura-maven-plugin

### ISSUE THREAD

**Issue by imagejan** [scijava/pom-scijava-base#7]
How about adding `cobertura-maven-plugin` in the `<reporting>` section of this POM, so that downstream projects can easily activate and use it to report code coverage of their tests?

```xml
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>cobertura-maven-plugin</artifactId>
	<version>2.6</version>
	<configuration>
		<formats>
			<format>html</format>
			<format>xml</format>
		</formats>
	</configuration>
</plugin>
```

What do you think?

**Comment by imagejan** [comment]
Thanks, @ctrueden!

I was wondering what the difference is between placing this in the `<build>` or in the `<reporting>` section (e.g. the javadoc plugin is in the latter, while most other plugins are in the former). Does it make any difference for downstream plugins when building with default goals (`mvn`)?

**Comment by ctrueden** [comment]
The `<reporting>` section is [used by the maven-site-plugin](https://maven.apache.org/plugins/maven-site-plugin/examples/configuring-reports.html)—i.e. when `mvn site` is run. It controls which plugins produce reports for your Maven-generated website. An example of such a website can be [seen here with maven-nar](https://maven-nar.github.io/).

I played with `mvn site` quite a bit in the early days of ImageJ2, but concluded it wasn't worth pursuing as a primary website generation mechanism. Additional thoughts about it are always welcome though.
